# Generated by Django 5.2.3 on 2025-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MHCapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalrecord",
            options={
                "permissions": [
                    ("can_add_record", "Can add medical record"),
                    ("can_view_record", "Can view medical record"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Pending Approval", "Pending Approval"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, verbose_name="Medical History"),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("doctor", "date_time")},
        ),
    ]
